[package]
name = "shu"
version = "1.0.2"
compiler = "0.15.0"
entrypoint = "lib.typ"
authors = ["Tieming Geng <https://github.com/yopming>"]
license = "GPLv3"
description = "template for books"

[template]
path = "template"
entrypoint = "main.typ"
